### ISSUE TITLE
from dokuwiki installation does'nt work

### ISSUE THREAD

**Issue by luffah** [justburn/DokuWiki_CacheRevisionsEraser#2]
I tried to install your plugin from extension manager in greebo.

(Using extension search)
It fails with warning "Error, the requested extension hasn't been installed or updated".

Too, informations in plugin.infos.txt are out to date.

( ... ok ... that is just too much complicated /  installation success if using one of the mirror in dropbox ... using plugin i got an error '`ERROR: Missing or imcompatible configurations file (ERR: 1)`)

^^ thx for your work

**Comment by justburner** [comment]
Totally forgot this project existed! Ops... wish could reply sooner.
I no longer actively maintaining this project since i don't use Dokuwiki anymore for many years.
Anyway according to the plugin's wiki page it say that it should be compatible with 2018-04-22 "Greebo"... maybe only automatic installation isn't compatible anymore??

According to that plugin error make sure the file **configs.php** was created alongside where the plugin was installed and is accessible by the plugin... if that files doesn't exist you can always rename **configs.in.php** to **configs.php** and modify that file if you need to limit/restrict any functionality.

Few years have passed since I've last tested it so i really recommend you to do a backup first, just in case.

Thanks for letting me know about this.
